sudo: false
language: node_js
node_js:
  - 'stable'
  - '8'
  - '6'
  - '4'
  - '0.12'
  - '0.10'
script:
  - npm test
  # Run browser tests on one node version.
  - [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [[ $(node -v) =~ ^v8.*$ ]] && npm run test:browsers
addons:
  sauce_connect: true
env:
  global:
  - secure: XcBiD8yReflut9q7leKsigDZ0mI3qTKH+QrNVY8DaqlomJOZw8aOrVuX9Jz12l86ZJ41nbxmKnRNkFzcVr9mbP9YaeTb3DpeOBWmvaoSfud9Wnc16VfXtc1FCcwDhSVcSiM3UtnrmFU5cH+Dw1LPh5PbfylYOS/nJxUvG0FFLqI=
  - secure: jNWtEbqhUdQ0xXDHvCYfUbKYeJCi6a7B4LsrcxYCyWWn4NIgncE5x2YbB+FSUUFVYfz0dsn5RKP1oHB99f0laUEo18HBNkrAS/rtyOdVzcpJjbQ6kgSILGjnJD/Ty1B57Rcz3iyev5Y7bLZ6Y1FbDnk/i9/l0faOGz8vTC3Vdkc=
